package com.probmatic.grapher;

import com.github.mikephil.charting.data.Entry;

import java.util.ArrayList;

public class HandlesParameters  {
    ArrayList<Entry> an_error = new ArrayList<>(); // Point showing disparity if user is off guide
    ArrayList<Entry> an_guide = new ArrayList<>(); // Plot generated by exerciseParameters
    ArrayList<Entry> an = new ArrayList<>();       // Plot tracking user motion
    ArrayList<Entry> end_zone = new ArrayList<>();       // Green end zone
    //5/4/21 Patch
    ArrayList<Entry> decline = new ArrayList<>(); // To get the cursor back on track if it falls off path
    float end_zone_threshold = 10;
    float top_zone_threshold_upper = 15;
    float top_zone_threshold_lower = 5;
    int an_color;
}
